language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc gfortran libx11-dev
  - git clone https://gitlab.com/relmendorp/avl.git
  - cd avl
  - make
  - cd bin
  - export PATH=$PATH:$(pwd)
  - cd ..
  - cd ..
install:
  - pip install -e ./
before_script:
  - pip install coveralls
script:
  - python ADR/main.py
  - coverage run --source=ADR -m pytest
after_script:
  - coveralls
