language: python
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install gcc gfortran libx11-dev
  - git clone https://gitlab.com/relmendorp/avl.git avl_repo
  - cd avl_repo
  - make
  - cd bin
  - export PATH=$PATH:$(pwd)
  - cd ..
  - cd ..
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install
before_script:
  - pip install coveralls
script:
  - coverage run -m pytest
after_script:
  - coveralls
