language: python
python:
  - "3.8"
before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
install:
  - poetry install
before_script:
  - pip install coveralls
script:
  - coverage run -m pytest
after_script:
  - coveralls
