plane_parameters_selector = {

    "plane_type":                   False,
    "wing1_x":                      False,
    "wing1_y":                      False,
    "wing1_z":                      False,
    "wing1_clmax_airfoil":          False,
    "wing1_airfoil1_name":          False,
    "wing1_airfoil2_name":          False,
    "wing1_airfoil3_name":          False,
    "wing1_span1":                  True,
    "wing1_span2":                  True,
    "wing1_chord1":                 True,
    "wing1_chord2":                 True,
    "wing1_chord3":                 True,
    "wing1_twist1":                 False,
    "wing1_twist2":                 False,
    "wing1_twist3":                 False,
    "wing1_incidence":              False,

    "wing2_x":                      False,
    "wing2_y":                      False,
    "wing2_z":                      True,
    "wing2_clmax_airfoil":          False,
    "wing2_airfoil1_name":          False,
    "wing2_airfoil2_name":          False,
    "wing2_airfoil3_name":          False,
    "wing2_span1":                  True,
    "wing2_span2":                  True,
    "wing2_chord1":                 True,
    "wing2_chord2":                 True,
    "wing2_chord3":                 True,
    "wing2_twist1":                 False,
    "wing2_twist2":                 False,
    "wing2_twist3":                 False,
    "wing2_incidence":              False,

    "hs_x":                         True,
    "hs_y":                         False,
    "hs_z":                         True,
    "hs_clmax_airfoil":             False,
    "hs_airfoil1_name":             False,
    "hs_airfoil2_name":             False,
    "hs_airfoil3_name":             False,
    "hs_span1":                     True,
    "hs_span2":                     True,
    "hs_chord1":                    True,
    "hs_chord2":                    True,
    "hs_chord3":                    True,
    "hs_twist1":                    False,
    "hs_twist2":                    False,
    "hs_twist3":                    False,
    "hs_incidence":                 False,

    "vs_x":                         False,
    "vs_y":                         False,
    "vs_z":                         False,
    "vs_clmax_airfoil":             False,
    "vs_airfoil1_name":             False,
    "vs_airfoil2_name":             False,
    "vs_airfoil3_name":             False,
    "vs_span1":                     False,
    "vs_span2":                     False,
    "vs_chord1":                    False,
    "vs_chord2":                    False,
    "vs_chord3":                    False,
    "vs_twist1":                    False,
    "vs_twist2":                    False,
    "vs_twist3":                    False,
    "vs_incidence":                 False,

    "motor_x":                      False,
    "motor_z":                      False,
    "static_thrust":                False,
    "linear_decay_coefficient":     False,

    "cg_x":                         True,
    "cg_z":                         False,

    "tpr_x":                        True,
    "tpr_z":                        False,

    "Iyy_TPR":                      False,
    "CD_tp":                        False,
    "S_tp":                         False,
    "CD_fus":                       False,
    "S_fus":                        False,
    "u_k":                          False,
}